

#pragma once

#include "NativeGameplayTags.h"

namespace PGGamePlayTags
{
	// INPUT Tags
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);	
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	
	PGDATA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
} 