

#pragma once

#include "NativeGameplayTags.h"

namespace PGGamePlayTags
{
	// Player Ability
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);

	// Enemy Ability
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_MeleeSkill);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_RangeSkill);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_HealSkill);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonSkill);

	// Shared Ability
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	// Weapon Tag
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sword);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Bow);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Staff);
	
} 