

#pragma once

#include "NativeGameplayTags.h"

namespace PGGamePlayTags
{
	// INPUT Tags
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip_Weapon);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

	// Event Tags
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Weapon);
	
} 