

#pragma once

#include "NativeGameplayTags.h"

namespace PGGamePlayTags
{
	// INPUT Tags
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip_Weapon);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Normal);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot1);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot2);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot3);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot4);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot5);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Slot6);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

	// Player Ability
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	
	// Event Tags
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Weapon);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Weapon);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);


	// Weapon Tag
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sword);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Bow);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Staff);


	// Shared Tags
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	PGSHARED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
} 